/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExtendRouteImport } from './routes/extend'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LoginCompleteRouteImport } from './routes/login.complete'
import { Route as AdminSchedulesRouteImport } from './routes/admin/schedules'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSettingsServicesRouteImport } from './routes/admin/settings/services'
import { Route as AdminSettingsSchedulesRouteImport } from './routes/admin/settings/schedules'
import { Route as AdminSettingsRetentionRouteImport } from './routes/admin/settings/retention'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/admin/settings/notifications'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtendRoute = ExtendRouteImport.update({
  id: '/extend',
  path: '/extend',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCompleteRoute = LoginCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => LoginRoute,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/admin/schedules',
  path: '/admin/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsServicesRoute = AdminSettingsServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsSchedulesRoute = AdminSettingsSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsRetentionRoute = AdminSettingsRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extend': typeof ExtendRoute
  '/login': typeof LoginRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/login/complete': typeof LoginCompleteRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/retention': typeof AdminSettingsRetentionRoute
  '/admin/settings/schedules': typeof AdminSettingsSchedulesRoute
  '/admin/settings/services': typeof AdminSettingsServicesRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extend': typeof ExtendRoute
  '/login': typeof LoginRouteWithChildren
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/login/complete': typeof LoginCompleteRoute
  '/admin': typeof AdminIndexRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/retention': typeof AdminSettingsRetentionRoute
  '/admin/settings/schedules': typeof AdminSettingsSchedulesRoute
  '/admin/settings/services': typeof AdminSettingsServicesRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extend': typeof ExtendRoute
  '/login': typeof LoginRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/login/complete': typeof LoginCompleteRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/retention': typeof AdminSettingsRetentionRoute
  '/admin/settings/schedules': typeof AdminSettingsSchedulesRoute
  '/admin/settings/services': typeof AdminSettingsServicesRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extend'
    | '/login'
    | '/admin/settings'
    | '/admin/jobs'
    | '/admin/schedules'
    | '/login/complete'
    | '/admin/'
    | '/admin/settings/notifications'
    | '/admin/settings/retention'
    | '/admin/settings/schedules'
    | '/admin/settings/services'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extend'
    | '/login'
    | '/admin/jobs'
    | '/admin/schedules'
    | '/login/complete'
    | '/admin'
    | '/admin/settings/notifications'
    | '/admin/settings/retention'
    | '/admin/settings/schedules'
    | '/admin/settings/services'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/extend'
    | '/login'
    | '/admin/settings'
    | '/admin/jobs'
    | '/admin/schedules'
    | '/login/complete'
    | '/admin/'
    | '/admin/settings/notifications'
    | '/admin/settings/retention'
    | '/admin/settings/schedules'
    | '/admin/settings/services'
    | '/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtendRoute: typeof ExtendRoute
  LoginRoute: typeof LoginRouteWithChildren
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminJobsRoute: typeof AdminJobsRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extend': {
      id: '/extend'
      path: '/extend'
      fullPath: '/extend'
      preLoaderRoute: typeof ExtendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/complete': {
      id: '/login/complete'
      path: '/complete'
      fullPath: '/login/complete'
      preLoaderRoute: typeof LoginCompleteRouteImport
      parentRoute: typeof LoginRoute
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/admin/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/services': {
      id: '/admin/settings/services'
      path: '/services'
      fullPath: '/admin/settings/services'
      preLoaderRoute: typeof AdminSettingsServicesRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/schedules': {
      id: '/admin/settings/schedules'
      path: '/schedules'
      fullPath: '/admin/settings/schedules'
      preLoaderRoute: typeof AdminSettingsSchedulesRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/retention': {
      id: '/admin/settings/retention'
      path: '/retention'
      fullPath: '/admin/settings/retention'
      preLoaderRoute: typeof AdminSettingsRetentionRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/notifications': {
      id: '/admin/settings/notifications'
      path: '/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
  }
}

interface LoginRouteChildren {
  LoginCompleteRoute: typeof LoginCompleteRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginCompleteRoute: LoginCompleteRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminSettingsRetentionRoute: typeof AdminSettingsRetentionRoute
  AdminSettingsSchedulesRoute: typeof AdminSettingsSchedulesRoute
  AdminSettingsServicesRoute: typeof AdminSettingsServicesRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminSettingsRetentionRoute: AdminSettingsRetentionRoute,
  AdminSettingsSchedulesRoute: AdminSettingsSchedulesRoute,
  AdminSettingsServicesRoute: AdminSettingsServicesRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtendRoute: ExtendRoute,
  LoginRoute: LoginRouteWithChildren,
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminJobsRoute: AdminJobsRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
